language: android
dist: trusty

notifications:
  email:
      - alessandro.crugnola@gmail.com

jdk:
  - oraclejdk8

env:
  global:
    - ANDROID_API_LEVEL=28
    - ANDROID_BUILD_TOOLS_VERSION=28.0.3

android:
  components:
      - tools
      - platform-tools
      - build-tools-$ANDROID_BUILD_TOOLS_VERSION
      - android-$ANDROID_API_LEVEL
      - extra-android-support
  licenses:
      - 'android-sdk-license-.+'

before_install:
  - chmod +x gradlew
  #  https://github.com/travis-ci/travis-ci/issues/8874#issuecomment-350350607
  - yes | sdkmanager "platforms;android-$ANDROID_API_LEVEL"

script:
  - ./gradlew build

branches:
  only:
    - master
    language: android
